### PR TITLE
fix(external): ensure solo soft predict returns probs

### LINKED ISSUE #2688: Document `SOLO.predict()` return values better.
The [documentation](https://docs.scvi-tools.org/en/stable/api/reference/scvi.external.SOLO.html#scvi.external.SOLO.predict
) reads:

> soft ([bool](https://docs.python.org/3/library/functions.html#bool) (default: True)) – Return probabilities instead of class label

However, the return values are not probabilities -- they range from -30 to 30 in my case. How should I interpret these? 

image

### PR DESCRIPTION
**Pull request by martinkim0**
closes #2688

### CODE REVIEW

**Comment by canergen** [comment]
It needs to be labeled as breaking change. It might be some folks use softmax after SOLO (I do). I guess it's better to also print a warning about the change for scVI-tools 1.3.

**Comment by martinkim0** [comment]
> It needs to be labeled as breaking change. It might be some folks use softmax after SOLO (I do). I guess it's better to also print a warning about the change for scVI-tools 1.3.

Right - I forgot to do that. This is slated to be released with 1.1.3, should we revert it then? It's technically a bug fix so IMO it should be fine.

**Comment by canergen** [comment]
I think it's fine to release with 1.1.3 and I prefer outputting probabilities. I agree the code was wrong and not the documentation. However, we should highlight this change as it might affect analysis scripts. I'm open whether it outputs a warning or not but the release note should contain a breaking change.

**Comment by martinkim0** [comment]
Makes sense! I'll add a warning and a note to the changelog.

**Pull request merged**
