### PR TITLE
Added PoissonVI Region Factors

### PR DESCRIPTION
**Pull request by ori-kron-wis**
This will close Issue [2529](https://github.com/scverse/scvi-tools/issues/2529)

### CODE REVIEW

**Review by canergen — COMMENTED** [review]
Is the bias optional? Please add changes to CHANGELOG.

**Comment by canergen** [comment]
@ori-kron-wis Can you do manual backport.

**Comment by ori-kron-wis** [comment]
> @ori-kron-wis Can you do manual backport.

why isn't the auto back porting not working for us (not just this PR)?

**Comment by canergen** [comment]
It's usually conflicts (mainly changelog). If you do it manually, it shows you merge conflicts when you want to merge the branch into 1.2.X.

**Comment by canergen** [comment]
If you want to dive deeper, there might be an option to flag files to keep both changes (incoming and existing) which is the correct policy for CHANGELOG.md but likely not for other files.

**Pull request merged**
