### PR TITLE
Test against Python 3.11

### LINKED ISSUE #1820: Support Python 3.11
PyTorch and Lightning currently do not support Python 3.11 [#86566](https://github.com/pytorch/pytorch/issues/86566).

### PR DESCRIPTION
**Pull request by adamgayoso**
Fixes #1820

### CODE REVIEW

**Comment by martinkim0** [comment]
@adamgayoso numba 0.57.0 was released yesterday but it looks like the latest Ray release does not support 3.11 still https://github.com/ray-project/ray/issues/33232

**Comment by martinkim0** [comment]
Ray 2.5 was released today, but this is now blocked by cellxgene-census. See https://github.com/chanzuckerberg/cellxgene-census/issues/526

**Review by martinkim0 — APPROVED** [review]
LGTM

**Comment by adamgayoso** [comment]
meeseeksdev backport to 1.0.x

**Pull request merged**
