### PR TITLE
nbsphinx dark mode

### PR DESCRIPTION
**Pull request by adamgayoso**
Fixes rendering of tables in tutorials in dark mode, removes unused css

### CODE REVIEW

**Review by jjhong922 — APPROVED** [review]

**Comment by adamgayoso** [comment]
@meekseeksdev backport to 0.15.x

**Comment by adamgayoso** [comment]
@meekseeksdev backport to 0.15.x

**Comment by adamgayoso** [comment]
@meekseeksdev backport 0.15.x

**Comment by adamgayoso** [comment]
@meeseeksdev backport 0.15.x

**Pull request merged**
