### PR TITLE
Ray Tune for hyperparameter optimization

### LINKED ISSUE #1720: Basic working API of autotuning with Ray Tune

### PR DESCRIPTION
**Pull request by martinkim0**
Continuing #1565 in a new staging branch. Closes #1720. This comment will be updated with some documentation regarding this PR (last updated: 10/07/2022).

In order to prepare a model class for interacting with the `scvi.autotune` module, a couple of changes are required in the current implementation:

- Models must implement a `classproperty` (available in `scvi._decorators`) called `_tunables`, which should list attributes that contain tunable elements, _e.g._ `SCVI`'s `self.module`, which is `scvi.module.VAE`.
- Tunable elements can be exposed by using the typing wrapper `Tunable` (available in `scvi.autotune._typing`. For example, the `VAE.__init__` will have `n_latent: Tunable[int]`. This will allow the `autotune` manager to discover these hyperparameters and mark them as available to the user.
- All user-provided search spaces will then be validated against a model's registry to see if hyperparameter names have been exposed with `Tunable`.

Other notes:

- `ModelTuner` instances are only attached to a model class, not a specific `anndata`. This will allow users to call `fit` multiple times on the same tuner with different anndatas.
- `fit_train` will fit and then fully train with the best model.
- Some thought needs to be given as to how progress will be printed to console. Ray Tune's `CLIReporter` currently gives way too much information.
- Still needs to be implemented: Validating model metrics during initialization and `fit`ing of `ModelTuner`s.
- Providing default search spaces for models will require a good amount of work. We can generate new PRs for each of these after a working implementation is present.

### CODE REVIEW

**Comment by martinkim0** [comment]
Currently running into an issue with Ray Tune integrations with PyTorch Lightning. It seems that when using an environment with Python 3.7, everything works fine, but when upgrading to anything 3.7>, Lightning models fail to train to completion, leading to Tune trials not completing. Steps to reproduce issue:
```
mamba create -n ray-37 python=3.7
mamba activate ray-37
mamba install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
mamba install -c conda-forge cudatoolkit-dev
mamba install jax jaxlib cuda-nvcc -c conda-forge -c nvidia
pip install "ray[tune]"
mamba install pytorch-lightning
mamba install ipykernel jupyter
python -m ipykernel install --user --name=ray-37
```
Repeat same process but for Python 3.8. Following the tutorial in [docs](https://docs.ray.io/en/latest/tune/examples/tune-pytorch-lightning.html), example works fine for 3.7 but goes on forever with 3.8. Both environments have the same versions of Ray and PyTorch Lightning.

Another (possible related) issue is that importing `scvi` before `ray` leads to kernel crashes.

**Comment by martinkim0** [comment]
Downgrading to `pytorch-lightning=1.6` solves issue, seems to be related to [#27493](https://github.com/ray-project/ray/issues/27493).

**Comment by adamgayoso** [comment]
@martinkim0 can you try a PR that changes our req of lightning to >=1.6,<1.8 and see if it passes?

**Comment by martinkim0** [comment]
> @martinkim0 can you try a PR that changes our req of lightning to >=1.6,<1.8 and see if it passes?

Sure

**Comment by martinkim0** [comment]
This PR is almost ready to merge. A couple of things still left:

- [ ] Allow for custom metrics to be passed in with a callback
- [ ] Integration with scib-metrics
- [ ] Resource setting, in particular GPUs
- [ ] Dummy defaults for models

**Comment by martinkim0** [comment]
Closing this PR since there are some changes that should not be included in this branch, but it's becoming hard to revert these changes. Will be opening multiple smaller PRs that should hopefully be easier to review.

**Pull request closed without merging**
