### PR TITLE
MultiVI protein

### PR DESCRIPTION
**Pull request by talashuach**
Adding surface-protein support for the MultiVI architecture

### CODE REVIEW

**Comment by adamgayoso** [comment]
@jjhong922 can you rebase and push this branch with a new name? After that @marianogabitto you can open a new PR using the new branch name

**Comment by marianogabitto** [comment]
Can you be more explicit ? what should I do ? Can Justin let me know what I should do ?

**Comment by adamgayoso** [comment]
@marianogabitto -- by wednesday @jjhong922 will have the branch in a state that is mergeable (incorporating our work the past few months). After that, you can reopen the PR where we will make comments

**Comment by jjhong922** [comment]
@marianogabitto The new branch can be found at `multivi-v15`. Let me know if you had questions, I had to tweak certain things on my end to make things work (e.g. introducing the `protein_exp_key` to `MULTVI.setup_anndata`.

**Pull request closed without merging**
