### PR TITLE
Remove softplus in AmortizedLDA for cell topic variance

### PR DESCRIPTION
**Pull request by jjhong922**
Tested in Colab
image

### CODE REVIEW

**Review by adamgayoso — APPROVED** [review]

**Comment by adamgayoso** [comment]
@meeseeksdev backport to 0.15.x

**Comment by adamgayoso** [comment]
@MeeseeksDev hello

**Comment by adamgayoso** [comment]
@meeseeksdev backport 0.15.x

**Comment by Carreau** [comment]
Can you retry ? It looks like the installation on PlasmaPy was suspended and that made the whole bot crash. It should be back.

**Comment by adamgayoso** [comment]
@meeseeksdev backport to 0.15.x

**Comment by adamgayoso** [comment]
@Carreau Thanks!

**Comment by Carreau** [comment]
Thank you for warning me.

**Pull request merged**
