### PR TITLE
feat(external): add velovi to external

### PR DESCRIPTION
**Pull request by martinkim0**
closes feature request #2610

### CODE REVIEW

**Comment by adamgayoso** [comment]
cc @WeilerP

**Comment by WeilerP** [comment]
@martinkim0, the idea was to have velovi as part of the `scvelo` package. Either way is fine for me, we should just only have one option, IMO. What do you think, @adamgayoso?

**Comment by adamgayoso** [comment]
So I'm mostly indifferent, I had forgotten about this. But a few thoughts:

1. I think it will be easier to maintain if it's in scvi-tools because then it's easier to integrate any API changes (so that @martinkim0 doesn't have to make PRs into scvelo).
2. In that scenario, scvelo would export the model here, special utilities could be removed from here and kept only in scvelo, and the docs here can point to the scvelo docs for complete usage.

But really I think either is fine. @martinkim0 perhaps you should revert this as we make a decision.

**Comment by WeilerP** [comment]
I think that's totally reasonable and the better option! Let's keep it here and I'll remove it from scvelo.

**Comment by martinkim0** [comment]
Great! So I'm going to keep this commit then but remove the utility functions (`get_permutation_scores` and `preprocess_data`) and open a PR to add them to scvelo. Does that sound good?

**Comment by WeilerP** [comment]
> Great! So I'm going to keep this commit then but remove the utility functions (`get_permutation_scores` and `preprocess_data`) and open a PR to add them to scvelo. Does that sound good?

Sounds good to me! Let's discuss everything else in the corresponding PR. Thanks in advance!

**Pull request merged**
