### PR TITLE
Faster inference in PyTorch with `torch.inference_mode`.

### LINKED ISSUE #1159: Faster inference in PyTorch
Apply this suggestion to our code where/if possible: https://twitter.com/PyTorch/status/1437838231505096708?s=20

### PR DESCRIPTION
**Pull request by martinkim0**
For the vast majority of cases, we can simply replace `torch.no_grad()` with `torch.inference_mode()` for speedup.  This mode reduces some of the overheads (version counting and metadata tracking) associated with `NoGrad`. Some notes:
- Tensors created during inference mode cannot be used in `Autograd` operations outside the mode, can be addressed by cloning the tensor
- Inference tensors cannot be modified in-place
- Higher speedups are more noticeable for smaller operations where overheads are relatively larger

Closes #1159.

### CODE REVIEW

**Comment by adamgayoso** [comment]
@martinkim0 can you try a simple benchmark of the code to see if it's faster? For example, take a trained scvi model on dummy data and run get_latent_representation with inference_mode versus no_grade with %timeit and report the results?

**Comment by martinkim0** [comment]
Great idea, I'll go ahead and do that and share results.

**Comment by martinkim0** [comment]
Here's a benchmark [notebook](https://colab.research.google.com/drive/1DD2fAw1A31G-ODHVeYBGJ-za3pia1Q1K?usp=sharing). Speedups are consistent but not that large.

**Review by adamgayoso — APPROVED** [review]
LGTM

**Pull request merged**
