### PR TITLE
Add batch distributed sampler support for `AnnDataLoader`

### LINKED ISSUE #1226: Multi GPU training
1. Write a custom [`DistributedSampler`](https://pytorch.org/docs/stable/data.html#torch.utils.data.distributed.DistributedSampler) that also takes as input the overall set of indices to pull data from (i.e., train set or test set or val set indices). Probably just need to add a few lines of code to init, call super init and the write a custom iter method
2. Use this sampler if multi gpu training selected (these are all through kwargs of pytorch lightning trainer)

### PR DESCRIPTION
**Pull request by martinkim0**
-   [x] Closes #1226 
-   [x] Tests added and passed if fixing a bug or adding a new feature
-   [x] All code checks passed.
-   [x] Added type annotations to new arguments/methods/functions.
-   [x] Added an entry in the latest `docs/release_notes/index.md` file if fixing a bug or adding a new feature.
-   [x] If the changes are patches for a version, I have added the `on-merge: backport to x.x.x` label.

## Changes

Adds `scvi.dataloaders._samplers.BatchDistributedSampler`, a wrapper class around `torch.utils.data.distributed.DistributedSampler` that allows us to access a minibatch with a single call to the dataset's getitem. This helps with efficient indexing into sparse arrays.

### CODE REVIEW

**Comment by bkmartinjr** [comment]
@martinkim0 - I will have a look.  I'm a newb so it will take me a bit to sort out how to use (I didn't see any sample code or tests that use it to train a model -- if I missed something, just LMK)

**Comment by martinkim0** [comment]
@bkmartinjr Ah sorry, I forgot to include an example of how to use this. You can use
```
model.train(strategy="ddp_find_unused_parameters_true")
```
and it will use the distributedsampler automatically. I'll also write some test cases covering training.

**Comment by bkmartinjr** [comment]
@martinkim0 - I have it working and so far no major issues.

I did notice that if I pass `earlystopping=True` to SCVI's `train()` method, it will generate an error.  Entirely possible this is my error.

```
Epoch 1/100:   1%|▋                                                                         | 1/100 [00:06<11:09,  6.77s/it, v_num=1, train_loss_step=733, train_loss_epoch=962]Traceback (most recent call last):
  File "/home/bruce/scvi/./multigpu.py", line 18, in <module>
    model.train(max_epochs=100, early_stopping=True, batch_size=4096, strategy="ddp_find_unused_parameters_true")
  File "/home/bruce/scvi-tools/scvi/model/base/_training_mixin.py", line 91, in train
    return runner()
  File "/home/bruce/scvi-tools/scvi/train/_trainrunner.py", line 99, in __call__
    self.trainer.fit(self.training_plan, self.data_splitter)
  File "/home/bruce/scvi-tools/scvi/train/_trainer.py", line 186, in fit
    super().fit(*args, **kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 531, in fit
    call._call_and_handle_interrupt(
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 41, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 91, in launch
    return function(*args, **kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 570, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 975, in _run
    results = self._run_stage()
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1018, in _run_stage
    self.fit_loop.run()
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 202, in run
    self.on_advance_end()
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 369, in on_advance_end
    call._call_callback_hooks(trainer, "on_train_epoch_end", monitoring_callbacks=True)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 189, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/callbacks/early_stopping.py", line 180, in on_train_epoch_end
    self._run_early_stopping_check(trainer)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/callbacks/early_stopping.py", line 191, in _run_early_stopping_check
    if trainer.fast_dev_run or not self._validate_condition_metric(  # disable early_stopping with fast_dev_run
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/callbacks/early_stopping.py", line 146, in _validate_condition_metric
    raise RuntimeError(error_msg)
RuntimeError: Early stopping conditioned on metric `elbo_validation` which is not available. Pass in or modify your `EarlyStopping` callback to use any of the following: `kl_weight`, `train_loss`, `train_loss_step`, `train_loss_epoch`, `elbo_train`, `reconstruction_loss_train`, `kl_local_train`, `kl_global_train`
```

**Comment by bkmartinjr** [comment]
Another question/issue: are other `ddp_*` strategies expected to work?  I found that:
* Works: ddp_spawn_find_unused_parameters_true, ddp_find_unused_parameters_true
* Fails:  ddp_fork_find_unused_parameters_true

Tested with SCVI model,  on the same config/host that works for other strategies.

`ddp_fork_find_unuxed_parameters_true` failure:
```
2023-06-14 14:09:14 1122652 INFO     Train model
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[rank: 0] Global seed set to 0
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
[rank: 1] Global seed set to 0
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
[W CUDAFunctions.cpp:109] Warning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (function operator())
[W CUDAFunctions.cpp:109] Warning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (function operator())
Traceback (most recent call last):
  File "/home/bruce/scvi/./multigpu.py", line 64, in <module>
    sys.exit(main())
  File "/home/bruce/scvi/./multigpu.py", line 36, in main
    model.train(
  File "/home/bruce/scvi-tools/scvi/model/base/_training_mixin.py", line 91, in train
    return runner()
  File "/home/bruce/scvi-tools/scvi/train/_trainrunner.py", line 99, in __call__
    self.trainer.fit(self.training_plan, self.data_splitter)
  File "/home/bruce/scvi-tools/scvi/train/_trainer.py", line 186, in fit
    super().fit(*args, **kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 531, in fit
    call._call_and_handle_interrupt(
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 41, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/strategies/launchers/multiprocessing.py", line 124, in launch
    while not process_context.join():
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/strategies/launchers/multiprocessing.py", line 147, in _wrapping_function
    results = function(*args, **kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 570, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 933, in _run
    self.strategy.setup_environment()
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/strategies/ddp.py", line 143, in setup_environment
    self.setup_distributed()
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/strategies/ddp.py", line 192, in setup_distributed
    _init_dist_connection(self.cluster_environment, self._process_group_backend, timeout=self._timeout)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/fabric/utilities/distributed.py", line 245, in _init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1024, in _new_process_group_helper
    backend_class = ProcessGroupNCCL(backend_prefix_store, group_rank, group_size, pg_options)
RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!```

**Comment by martinkim0** [comment]
@bkmartinjr 

Re: DDP strategies
`"ddp_fork_find_unused_parameters_true"` does not work since the CUDA backend does not support the fork start method in multiprocessing, see [this article](https://pytorch.org/docs/stable/notes/multiprocessing.html). 

Re: Early stopping metrics
Looks like `"elbo_validation"` is not being logged in the model history. I'll take a look as to why this occurring - we might have updated the key or its not being logged for some reason. For now, I would pass in:
```
model.train(
    early_stopping=True,
    early_stopping_monitor="validation_loss",
    check_val_every_n_epoch=1,
)
```

**Comment by martinkim0** [comment]
Need to add support for concat and semisupervised dataloaders

**Comment by martinkim0** [comment]
Left to do:

- [ ] Add `sync_dist` when distributed mode is enabled
- [ ] Add more comprehensive tests

**Comment by martinkim0** [comment]
The simulated distributed tests are causing the tests to time out. Not sure exactly what the source is, but it might be best to make these tests optional.

**Pull request merged**
