### PR TITLE
Add normal distribution modelling of scVI for handling log-normalized data

### PR DESCRIPTION
**Pull request by HelloWorldLTY**
Hi, I have implemented a normal-distribution-based scVI to handle data after log-normalization. Would you please review it? I have tested the clustering performance of it and it looks good. Thanks.

### CODE REVIEW

**Review by martinkim0 — CHANGES_REQUESTED** [review]
Hi, thanks for your contribution. Looks good so far - could you add the following please:

- A release note in `CHANGELOG.md`
- Tests
- Possibly a small benchmark notebook showing how it performs vs. other distributions

**Comment by HelloWorldLTY** [comment]
Hi, I have modified the changelog. 

For the tests, I am a bit confused. It seems that I had I/O error, how to address it?

For the testing, shall I directly use the datasets from the tutorial? Do you have any recommendation? Thanks a lot.

**Comment by martinkim0** [comment]
Hi @HelloWorldLTY, thanks so much for this initial PR! I've merged #2780 that adds support for this (I updated the docstrings and changelog).

**Comment by HelloWorldLTY** [comment]
Thanks a lot.

**Pull request closed without merging**
