### PR TITLE
Pbmc

### PR DESCRIPTION
**Pull request by Edouard360**
Just adding the Purified PBMCs dataset

### CODE REVIEW

**Comment by jeff-regier** [comment]
Looks good, but will rebase on master rather than merge master?

**Comment by jeff-regier** [comment]
i.e.,

First, to drop the merge commit,
```
git reset HEAD~
git checkout -- .
```

Then, to rebase on master,
```
git fetch origin master
git rebase origin/master
```

Then to force push the changes,
```
git push -f origin pbcm
```

**Comment by jeff-regier** [comment]
(It doesn't matter that much, but it's a good practice to rebase rather than merge for this case. See how this PR is listed as adding +4,551 new lines of code?)

**Comment by Edouard360** [comment]
Thanks I wasn't sure if I had to force push

**Comment by Edouard360** [comment]
Thank you it seems it has worked but actually the n lines of code, come from the other subsampled  purified datasets from 10X that I had to add: ie:
   "cd14_monocytes",
                       "b_cells",
                       "cd34",
                       "cd56_nk",
                       "cd4_t_helper",
                       "regulatory_t",
                       "naive_t",
                       "memory_t",
                       "cytotoxic_t",
                       "naive_cytotoxic"

**Comment by Edouard360** [comment]
Or maybe we'd rather skip unit test for that one, in which case I can remove them all

**Comment by jeff-regier** [comment]
I see. Can we just include ~ten lines in the test files?

**Comment by Edouard360** [comment]
Ah maybe with symbolic links ?

**Comment by jeff-regier** [comment]
Symbolic links are all platform specific. Better not to use them in a git repo.

**Comment by jeff-regier** [comment]
Is it just test data you're putting in the test directory? If it's an actual dataset, not test dataset, you could add it to scvi-data: https://github.com/YosefLab/scVI-data/

**Comment by Edouard360** [comment]
Okok, it just that all the samples in "test/data/10X/" have the same structure and instead of duplicating the folders for each dataset we could just create the references no ? Creating the link before the travis build wouldn't make it work ?

**Comment by Edouard360** [comment]
It is just for testing - the dataset is a concat of multiple 10X datasets just like in pbmc.py (pbmc4k, pbmc8k), but here there are many more (around 10).

**Comment by jeff-regier** [comment]
unit tests are supposed to be quick running --- better to just test it as well as possible with just a tiny file of testing data (e.g., < 100 entries).

**Pull request merged**
